### ISSUE TITLE
ext:form support - Missing submit button label 

### ISSUE THREAD

**Issue by Fanor51** [TYPO3-Headless/headless#451]
Hello everybody!

Is there a way to get the submit button Label in the form json?
At the moments it looks like its missing. F.E:

![image](https://user-images.githubusercontent.com/10448557/177126869-0a37154c-14ca-4b62-88d3-e6bea11fea71.png)

I tried this with this simple TYPO3 Form configuration:

```
renderingOptions:
  submitButtonLabel: Submit
identifier: headless_test
label: Headless_test
type: Form
prototypeName: standard
finishers:
  -
    options:
      subject: 'Your message: {subject}'
      recipients:
        your.company@example.com: 'Your Company name'
      senderAddress: '{email}'
      senderName: '{name}'
      format: html
      attachUploads: true
      translation:
        language: default
      useFluidEmail: true
      title: 'Confirmation of your message'
    identifier: EmailToReceiver
renderables:
  -
    renderingOptions:
      previousButtonLabel: 'Previous step'
      nextButtonLabel: 'Next step'
    identifier: page-1
    label: 'Contact Form'
    type: Page
    renderables:
      -
        defaultValue: ''
        identifier: name
        label: Name
        type: Text
        properties:
          fluidAdditionalAttributes:
            placeholder: Name
        validators:
          -
            identifier: NotEmpty
      -
        defaultValue: ''
        identifier: subject
        label: Subject
        type: Text
        properties:
          fluidAdditionalAttributes:
            placeholder: Subject
        validators:
          -
            identifier: NotEmpty
      -
        defaultValue: ''
        identifier: email
        label: Email
        type: Text
        properties:
          fluidAdditionalAttributes:
            placeholder: 'Email address'
        validators:
          -
            identifier: NotEmpty
          -
            identifier: EmailAddress
      -
        defaultValue: ''
        identifier: message
        label: Message
        type: Textarea
        properties:
          fluidAdditionalAttributes:
            placeholder: ''
        validators:
          -
            identifier: NotEmpty
  -
    renderingOptions:
      previousButtonLabel: 'Previous step'
      nextButtonLabel: 'Next step'
    identifier: summarypage
    label: 'Summary page'
    type: SummaryPage
```

And i was searching for this area in the frontend json:

```
renderingOptions:
  submitButtonLabel: Submit

```

I tried to debug this a little bit and it looks to me like there is missing to add renderingOptions to the decorated elements in:
public/typo3conf/ext/headless/Classes/Form/Decorator/AbstractFormDefinitionDecorator.php Line 33

![image](https://user-images.githubusercontent.com/10448557/177127378-4959f0aa-b526-4de4-9440-0b70693b6838.png)

Is there a reason for not doing this? If not i can create a PR with a little fix to this if wanted.

- TYPO3: v11.5.12
- headless: v3.0.4
- PHP: 8.0.16

Thanks for the help and best regards
Fabio

**Comment by twoldanski** [comment]
Hi @Fanor51, 
by default we do not output renderingOptions, sometimes you could pass there some options to form which could have some sensitive info etc, and we do not want to expose via public API. The same way some standard decorator hides some things before returning definition to fronted. 

I added special section handled by default to handle labels/buttons etc 

Add section to form like this:

```
i18n:
  identifier: i18n
  properties:
    submitButton: your submit Label
```
it will be automatically translated via standard form handler for translations. 

BTW You could override it in your projects anytime, we have very flexible API to handle forms, ext:headless prepares only boilerplate template to let you quickly start project, but you do need to stick to it if you prefer different approach.
