### ISSUE TITLE
[BUG] Languages / headless.frontendUrls / frontendBase

### ISSUE THREAD

**Issue by kubilaymelnikov** [TYPO3-Headless/headless#538]
The `frontendBase` within a language, in the Configuration, is not respected.

Usecase: Multilanguage website with different domains.

```yaml
# Example Config
base: 'https://content.example.de/'
frontendBase: 'https://www.example.de/'
baseVariants:
  -
    base: 'http://example.ddev.site/'
    condition: 'applicationContext == "Development/DDEV"'
    languages:
      -
        languageId: 0
        base: /
      -
        languageId: 1
        base: https://content.example-en.de/
        frontendBase: 'https://www.example-en.de/'
        baseVariants:
          -
            base: 'http://example-en.ddev.site/'
            condition: 'applicationContext == "Development/DDEV"'
      -
        languageId: 2
        base: https://content.example-fr.de/
        frontendBase: 'https://www.example-fr.de/'
        baseVariants:
          -
            base: 'http://example-fr.ddev.site/'
            condition: 'applicationContext == "Development/DDEV"'
```

My current bug arises here `FriendsOfTYPO3\Headless\XClass\Typolink\PageLinkBuilder`
