### ISSUE TITLE
`frontendBase` ignored in SiteLanguages

### ISSUE THREAD

**Issue by schloram** [TYPO3-Headless/headless#674]
**Describe the bug**
I'm not sure if I'm doing something wrong or misunderstanding the concept of the `frontendUrl` config but I can't really figure out how it should work. For me it looks like as if the `frontendBase` config inside languages does not really work. Or at least for the PreviewUri functionality.

**To Reproduce**
My SiteConfig (for now please only pay attention to the `'applicationContext == "Development"'` variant):
```yaml
base: /
frontendBase: 'https://production-frontend.de'
baseVariants:
  -
    base: 'https://content-service.ddev.site'
    frontendBase: 'https://de.frontend.ddev.site'
    condition: 'applicationContext == "Development"'
headless: true
languages:
  -
    title: de_DE
    enabled: true
    languageId: 0
    base: /de/
    frontendBase: /
    locale: de_DE
    navigationTitle: Deutsch
    flag: de
    hreflang: ''
    websiteTitle: ''
    baseVariants:
      -
        base: /de/
        frontendBase: /
        condition: 'applicationContext == "Development"'
  -
    title: de_AT
    enabled: true
    locale: de_AT
    hreflang: ''
    base: /at/
    frontendBase: 'https://production-frontend.at'
    websiteTitle: ''
    navigationTitle: Österreichisch
    fallbackType: strict
    fallbacks: ''
    flag: at
    languageId: 1
    baseVariants:
      -
        base: /at/
        frontendBase: 'https://at.frontend.ddev.site'
        condition: 'applicationContext == "Development"'
rootPageId: 1
websiteTitle: ''
```

**Expected behavior**
I expect my urls to be as follows:
  - DE (Default):
    - Frontend: https://de.frontend.ddev.site
    - Backend: https://content-service.ddev.site/de/
  - AT:
    - Frontend: https://at.frontend.ddev.site
    - Backend: https://content-service.ddev.site/at/

When clicking the "Preview webpage" icon (![image](https://github.com/TYPO3-Headless/headless/assets/13196174/259d007c-3860-4b50-a75c-8480feb6cfad))  on an translated page I expect it to go to the url `https://at.frontend.ddev.site`. Instead I'm being redirected to `https://content-service.ddev.site/at/`

Am I misunderstanding the use-case of `frontendUrl` in general? Plus: Why isn't there a `frontenUrl` field in every SiteLanguage? That's why the manually added config always gets removed after saving vie backend module.

**Screenshots**

**TYPO3 version and TYPO3 Headless version**
TYPO3: 12.4.7
Headless: 4.2.2 (with flag `headless.frontendUrls` set to `true`)

**Additional context**
Add any other information related to the problem here.
